"""
Shared definitions for the Cozmo preprocessing pipeline.

Layout (relative to the dataset root, the parent of this directory):

    raw/                      inputs, never modified
    animations/json/<clip_name>.json   one clip per file, stem == clip Name
    animations/npz/<clip_name>.npz     resampled channel arrays, same stems
    labels.csv                one aggregated annotation row per clip
    REPORT.md                 regenerated by run_all.py

Every stage imports from here so there is exactly one definition of paths,
the CSV repair, and the name canonicalization.
"""

import csv
import os
import pathlib
import sys

PIPE_DIR = pathlib.Path(__file__).resolve().parent
ROOT = PIPE_DIR.parent

RAW_DIR = ROOT / "raw"
RAW_CSV = RAW_DIR / "cozmo_animation_labels.csv"
BIN_DIR = RAW_DIR / "assets" / "cozmo_resources" / "assets" / "animations"

ANIM_DIR = ROOT / "animations"
CLIPS_DIR = ANIM_DIR / "json"
NPZ_DIR = ANIM_DIR / "npz"
LABELS_CSV = ROOT / "labels.csv"
REPORT_MD = ROOT / "REPORT.md"

EMOTIONS = ['interest', 'alarm', 'confusion', 'understanding', 'frustration',
            'relief', 'sorrow', 'joy', 'anger', 'gratitude', 'fear', 'hope',
            'boredom', 'surprise', 'disgust', 'desire']

# Raw CSV column order; the first column is unnamed in the file.
CSV_COLUMNS = (['orig_row', 'batch', 'file_name', 'embed_code', 'video_id',
                'description'] + EMOTIONS)

FULL_WIDTH = len(CSV_COLUMNS)              # 22
HEAD_WIDTH = 6                             # fragment ending mid-description
TAIL_WIDTH = FULL_WIDTH - HEAD_WIDTH + 1   # 17: description tail + emotions


def import_pycozmo():
    """Import pycozmo with the Python-3.13 chunk shim and PYCOZMO_DIR set.

    pycozmo resolves its asset directory from $PYCOZMO_DIR/assets, so
    pointing it at raw/ finds the existing download.
    """
    os.environ.setdefault("PYCOZMO_DIR", str(RAW_DIR))
    shim = str(PIPE_DIR / "shim")
    if shim not in sys.path:
        sys.path.insert(0, shim)
    import pycozmo  # noqa: F401
    return pycozmo


def canonical_name(file_name: str) -> str:
    """Canonical clip name from a CSV file_name value.

    Undoes the mangling present in ~400 rows: underscores replaced by spaces,
    the minus sign in `head_angle_-20` dropped (leaving a double space), and
    strips the `.avi` extension.
    """
    s = os.path.splitext(file_name)[0]
    s = s.replace('  ', ' -')   # "head angle  20" -> "head angle -20"
    return s.replace(' ', '_')


def read_repaired_csv(csv_path=None):
    """
    Parse the raw labels CSV, stitching rows that were split across physical
    lines by unescaped newlines inside `description`.

    A split row appears as a 6-field fragment, zero or more 1-field
    fragments, then a 17-field fragment. Returns (rows, n_repaired) where
    rows are dicts keyed by CSV_COLUMNS. Raises ValueError if the file does
    not match this damage pattern or if the post-repair integrity check
    fails, rather than guessing.
    """
    csv_path = csv_path or RAW_CSV
    with open(csv_path, newline='') as f:
        raw = list(csv.reader(f))
    body = raw[1:]

    rows, repaired = [], 0
    i = 0
    while i < len(body):
        r = body[i]
        if len(r) == FULL_WIDTH:
            rows.append(r)
            i += 1
            continue
        if len(r) != HEAD_WIDTH:
            raise ValueError(
                f"{csv_path}:{i + 2}: unexpected {len(r)}-field row")
        j = i + 1
        while j < len(body) and len(body[j]) == 1:
            j += 1
        if j >= len(body) or len(body[j]) != TAIL_WIDTH:
            raise ValueError(
                f"{csv_path}:{i + 2}: {HEAD_WIDTH}-field fragment with no "
                f"{TAIL_WIDTH}-field continuation")
        parts = [r[5]] + [body[k][0] for k in range(i + 1, j)] + [body[j][0]]
        rows.append(r[:5] + ['\n'.join(parts)] + body[j][1:])
        repaired += 1
        i = j + 1

    # The unnamed index column is sequential in the undamaged file; after a
    # correct repair it must be exactly 0..n-1. This catches any misalignment.
    idx = [r[0] for r in rows]
    if idx != [str(k) for k in range(len(rows))]:
        raise ValueError("index column not sequential after repair; "
                         "the CSV damage pattern has changed")

    return [dict(zip(CSV_COLUMNS, r)) for r in rows], repaired


def clip_stems() -> set:
    """Stems of the per-clip JSON files currently in animations/json/."""
    return {p.stem for p in CLIPS_DIR.glob("*.json")}
