#!/usr/bin/env python3
"""
Run the full Cozmo preprocessing pipeline and regenerate REPORT.md.

    raw/  ->  animations/{json,npz}/  +  labels.csv  (+ REPORT.md)

Stages:
    s1_extract    .bin containers -> one JSON per clip (exact-name files)
    s2_labels     raw CSV -> repaired, cleaned, one aggregated row per clip
    s3_bijection  prune both sides until labels <-> clips is a strict 1:1
    s4_npz        clips -> uniform 33 ms channel arrays

Deterministic: no timestamps or randomness anywhere, so a re-run from the
same raw/ produces byte-identical animations/json/, labels.csv and REPORT.md (npz
bytes differ only in zip metadata; array contents are identical).
"""

import sys

import cozmo_common as C
import s1_extract
import s2_labels
import s3_bijection
import s4_npz


def main():
    report = [
        "# Cozmo retargeting dataset — preprocessing report",
        "",
        "Generated by `data_preprocessing_pipeline/run_all.py`. Regenerate "
        "with:",
        "",
        "```",
        "/home/oren/miniconda3/bin/python data_preprocessing_pipeline/run_all.py",
        "```",
        "",
        "Inputs (never modified): `raw/assets/` (pycozmo 0.8.0 resource "
        "download, Cozmo app 3.4.0 OBB) and `raw/cozmo_animation_labels.csv` "
        "(crowd emotion annotations of clip videos; `embed_code` = YouTube "
        "video id).",
        "",
        "Outputs: `animations/json/<clip_name>.json` (keyframe ground truth, one clip "
        "per file), `labels.csv` (one aggregated annotation row per clip), "
        "`animations/npz/<clip_name>.npz` (derived 33 ms channel arrays). "
        "**Invariant: labels.csv `clip_name`, animations/json/ stems and animations/npz/ stems "
        "are identical sets — a strict bijection, enforced in stage 3 and "
        "asserted again at the end of the run.**",
        "",
    ]

    stats = {}
    stats['s1'] = s1_extract.run(report)
    print(f"s1_extract   : {stats['s1']}")
    stats['s2'] = s2_labels.run(report)
    print(f"s2_labels    : {stats['s2']}")
    stats['s3'] = s3_bijection.run(report)
    print(f"s3_bijection : {stats['s3']}")
    stats['s4'] = s4_npz.run(report)
    print(f"s4_npz       : {stats['s4']}")

    # Final three-way bijection assertion across all outputs.
    import csv
    with open(C.LABELS_CSV, newline='') as f:
        label_names = {r['clip_name'] for r in csv.DictReader(f)}
    clip_names = C.clip_stems()
    npz_names = {p.stem for p in C.NPZ_DIR.glob("*.npz")}
    if not (label_names == clip_names == npz_names):
        sys.exit(f"ERROR: final bijection check failed: "
                 f"{len(label_names)} labels / {len(clip_names)} clips / "
                 f"{len(npz_names)} npz")

    report += [
        "## Final state",
        "",
        f"- **{len(label_names)} clips**, each with exactly one labels.csv "
        "row, one animations/json/*.json file and one animations/npz/*.npz file, all under the "
        "same exact name",
        f"- annotations aggregated: {stats['s2']['annotations']}",
        f"- resampled frames: {stats['s4']['frames']}",
        "",
    ]
    with open(C.REPORT_MD, "w") as f:
        f.write("\n".join(report))
    print(f"\nbijection OK: {len(label_names)} labels == "
          f"{len(clip_names)} clips == {len(npz_names)} npz")
    print(f"wrote {C.REPORT_MD}")


if __name__ == "__main__":
    main()
