"""
Full-corpus retarget runs: the per-run driver (run_all), the single-clip
debug path (run_single), and the per-run RETARGET_REPORT.md writer.
"""

import json
import math
import sys
import time

import numpy as np

from config import (DT, DYN_SAMPLE, HOME4, LIMIT_MARGIN, MAPPING_VERSION,
                    NPZ_IN, PREVIEW, RATE_CAP, SCRATCH_RUN)
from labels import EMOTIONS, load_labels, top_emotions
from lamp_model import Lamp
from mapping import constants_sha1, mapping_constants, retarget_clip
from media import pick_gif_samples, render_gif, render_keypose_sheet
from runs import run_dir
from verify import check_determinism, dynamics_check, verify_clip


def fmt_r(r):
    return "n/a" if r is None else f"{r:+.2f}"


def run_all(args):
    run = args.run or str(int(time.time()))
    out_dir = run_dir(run)
    if run == SCRATCH_RUN:
        sys.exit(f"'{SCRATCH_RUN}' is reserved for single-clip debug output")
    if out_dir.exists() and any(out_dir.iterdir()):
        sys.exit(f"run dir {out_dir} already exists -- pick a new --run name"
                 f" (existing runs are kept for cross-run diffs)")
    lamp = Lamp()
    labels = load_labels()
    stems = sorted(p.stem for p in NPZ_IN.glob("*.npz"))
    assert set(stems) == set(labels), "source npz != labels.csv clip set"

    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"run '{run}' -> {out_dir}")

    metrics = {}
    for i, stem in enumerate(stems):
        z, f, arrays = retarget_clip(stem, lamp)
        np.savez_compressed(out_dir / f"{stem}.npz", **arrays)
        metrics[stem] = verify_clip(z, arrays, lamp)
        if (i + 1) % 100 == 0:
            print(f"  {i + 1}/{len(stems)} clips")

    out_stems = sorted(p.stem for p in out_dir.glob("*.npz"))
    assert out_stems == stems, "output bijection broken"
    print(f"bijection OK: {len(stems)} source == {len(out_stems)} retargeted"
          f" == {len(labels)} labels")

    dyn = []
    if not args.skip_dynamics:
        n = len(stems) if args.dynamics_all else DYN_SAMPLE
        stride = max(1, len(stems) // n)
        sample = stems[::stride][:n]
        print(f"dynamics check on {len(sample)} clips ...")
        dyn = dynamics_check(sample, lamp, out_dir, log=lambda s: None)
        worst = max(r[1].max() for r in dyn)
        print(f"  worst per-joint RMS tracking error: {worst:.2f} deg")

    picks = pick_gif_samples(labels)
    render_keypose_sheet(lamp, PREVIEW / "keyposes.png")
    for stem in picks:
        arrays = dict(np.load(out_dir / f"{stem}.npz"))
        render_gif(stem, arrays, labels, lamp, PREVIEW / f"{stem}.gif")

    write_report(stems, metrics, dyn, picks, labels, lamp, out_dir, run)

    if args.check_determinism:
        check_determinism(stems, lamp, out_dir)

    # written last: marks the run complete for downstream tools
    (out_dir / "run.json").write_text(json.dumps(dict(
        run=run,
        mapping_version=MAPPING_VERSION,
        constants_sha1=constants_sha1(json.dumps(mapping_constants(lamp))),
        created_at=int(time.time()),
        n_clips=len(stems)), indent=2) + "\n")
    print(f"run '{run}' complete ({len(stems)} clips)")


def write_report(stems, metrics, dyn, picks, labels, lamp, out_dir, run):
    n = len(stems)
    sat = np.stack([metrics[s]["sat"] for s in stems])
    rates = [metrics[s]["max_rate"] for s in stems]
    rh = [metrics[s]["r_head"] for s in stems if metrics[s]["r_head"]
          is not None]
    rl = [metrics[s]["r_lift"] for s in stems if metrics[s]["r_lift"]
          is not None]
    ry = [metrics[s]["r_yaw"] for s in stems if metrics[s]["r_yaw"]
          is not None]

    def med(v):
        return sorted(v)[len(v) // 2] if v else float("nan")

    worst_sat = sorted(stems, key=lambda s: -metrics[s]["sat"].max())[:10]

    # per-emotion mean joint speed (deg/s), over clips with fraction >= 0.5
    emo_rows = []
    for emo in EMOTIONS:
        sel = [s for s in stems if float(labels[s][emo]) >= 0.5]
        if not sel:
            continue
        speeds = []
        for s in sel:
            q = np.load(out_dir / f"{s}.npz")["qpos"]
            if len(q) > 1:
                speeds.append(np.degrees(np.abs(np.diff(q, axis=0)) / DT)
                              .mean())
        if speeds:
            emo_rows.append((emo, len(sel), float(np.mean(speeds))))

    lines = [
        "# Cozmo -> lamp retargeting report",
        "",
        f"Run **{run}**, generated by `data/lamp_retargeting/pipeline.py retarget --all`. A fresh run:",
        "",
        "```",
        "uv run data/lamp_retargeting/pipeline.py retarget --all --run <new-name>",
        "```",
        "",
        f"Mapping version **{MAPPING_VERSION}**. Feature-space retargeting: "
        "Cozmo's expressive features (turns, lift posture, drive, head "
        "angle, face tilt, gaze, eye openness) are re-synthesized as poses "
        "of the 5-DOF lamp (J1 yaw, J2/J3 shoulder+elbow posture synergy, "
        "J4 head tilt, J5 head nod) plus a light01 LED channel. See the "
        "docstring of data/lamp_retargeting/pipeline.py for the full channel table and "
        "rationale; `preview/keyposes.png` shows the calibrated keyposes.",
        "",
        "## Calibration (computed from assets/robot.xml at load, asserted)",
        "",
        f"- level-gaze nod position: q5 = {lamp.gaze_level_q5:.3f} rad at "
        f"HOME4 = {HOME4} (wrist roll that levels the nod axis)",
        f"- posture->gaze coupling: d(elev)/d(q2,q3) = "
        f"({lamp.pitch_coef[0]:+.3f}, {lamp.pitch_coef[1]:+.3f}), linear "
        "(J2/J3 axes are exactly antiparallel); the nod compensates it so "
        "gaze tracks Cozmo's head angle independent of crouch/lean",
        "",
        "## Verification",
        "",
        f"- **{n} clips retargeted**; output stems == source stems == "
        "labels.csv clip names (strict bijection, asserted)",
        f"- joint limits: all frames inside range (asserted; targets are "
        f"clipped {math.degrees(LIMIT_MARGIN):.0f} deg inside the hard "
        "limits). Pre-clip saturation fraction, corpus mean per joint "
        f"J1..J5: {', '.join(f'{x:.1%}' for x in sat.mean(axis=0))}",
        f"- worst-saturating clips: "
        + ", ".join(f"{s} ({metrics[s]['sat'].max():.0%})"
                    for s in worst_sat[:5]),
        f"- rate cap {RATE_CAP} rad/s: max observed "
        f"{max(rates):.2f} rad/s (asserted)",
        f"- semantic correlation (FK-based, clips where the source channel "
        "is animated):",
        f"  - lamp gaze elevation ~ Cozmo head angle: median "
        f"{med(rh):+.2f} over {len(rh)} clips",
        f"  - lamp head height ~ Cozmo lift height: median "
        f"{med(rl):+.2f} over {len(rl)} clips",
        f"  - lamp base yaw ~ Cozmo body yaw: median "
        f"{med(ry):+.2f} over {len(ry)} clips",
    ]
    for key, vals, label, note in (
            ("r_head", rh, "gaze~head", ""),
            ("r_lift", rl, "height~lift",
             " (expected: the head-down slump also lowers the head, "
             "diluting pure lift correlation by design - see K_SLUMP)"),
            ("r_yaw", ry, "yaw~yaw", "")):
        nlow = sum(1 for v in vals if v < 0.5)
        lines.append(f"  - {label} below 0.5: {nlow}/{len(vals)}{note}")
    if dyn:
        rms_all = np.stack([r[1] for r in dyn])
        max_all = np.stack([r[2] for r in dyn])
        worst_i = int(rms_all.max(axis=1).argmax())
        lines += [
            f"- dynamic feasibility (welded base, sts3215 position "
            f"actuators, 10 ms steps, {len(dyn)} clips): per-joint RMS "
            f"tracking error mean {rms_all.mean():.2f} deg, worst clip "
            f"{dyn[worst_i][0]} (RMS {rms_all[worst_i].max():.2f} deg, "
            f"max {max_all[worst_i].max():.2f} deg)",
        ]
    lines += [
        "",
        f"## Output format (data/lamp_retargeting/npz/{run}/<clip>.npz)",
        "",
        "| key | shape | meaning |",
        "|---|---|---|",
        "| t | (T,) | seconds, 33 ms grid (same grid as the source clip) |",
        "| qpos | (T,5) | joint targets J1..J5, rad |",
        "| light01 | (T,) | LED intensity from Cozmo eye openness, 0..1 |",
        "| rgb | (T,3) | backpack LED mean color |",
        "| audio_t / audio_ids / audio_vol | sparse | Wwise events, "
        "passthrough |",
        "| sat_frac | (5,) | pre-clip limit-saturation fraction per joint |",
        "| mapping_version / mapping_constants | scalars | provenance |",
        "",
        "## Motion by emotion (clips with annotator fraction >= 0.5)",
        "",
        "| emotion | clips | mean joint speed (deg/s) |",
        "|---|---|---|",
    ]
    for emo, cnt, spd in sorted(emo_rows, key=lambda r: -r[2]):
        lines.append(f"| {emo} | {cnt} | {spd:.1f} |")
    lines += [
        "",
        "## Previews (data/lamp_retargeting/preview/)",
        "",
        "- `keyposes.png` - calibrated keypose sheet",
    ]
    for s in picks:
        emo = top_emotions(labels[s], k=2)
        lines.append(f"- `{s}.gif` - {emo}")
    lines.append("")
    report_md = out_dir / "RETARGET_REPORT.md"
    report_md.write_text("\n".join(lines))
    print(f"wrote {report_md}")


def run_single(args):
    lamp = Lamp()
    stem = args.clip
    if not (NPZ_IN / f"{stem}.npz").exists():
        sys.exit(f"no such clip: {stem} (looked in {NPZ_IN})")
    labels = load_labels()
    z, f, arrays = retarget_clip(stem, lamp)
    out_dir = run_dir(SCRATCH_RUN)
    out_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out_dir / f"{stem}.npz", **arrays)
    print(f"wrote {out_dir / (stem + '.npz')}")
    m = verify_clip(z, arrays, lamp)
    print(f"frames {m['frames']}  dur {m['dur']:.2f}s  "
          f"max rate {m['max_rate']:.2f} rad/s")
    print(f"pre-clip saturation J1..J5: "
          + ", ".join(f"{x:.1%}" for x in m["sat"]))
    print(f"corr gaze~head {fmt_r(m['r_head'])}   "
          f"height~lift {fmt_r(m['r_lift'])}   yaw~yaw {fmt_r(m['r_yaw'])}")
    if not args.skip_dynamics:
        dyn = dynamics_check([stem], lamp, out_dir)
    if not args.no_gif:
        render_gif(stem, arrays, labels, lamp, PREVIEW / f"{stem}.gif")
